[package]

name = "Haiku Maker"
version = "0.0.1"
authors = [ "Eoin Kelly <eoin@rabidtech.co.nz>" ]

[[bin]]

name = "haiku_maker"

[dependencies.http]

git = "https://github.com/chris-morgan/rust-http"
