version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - "cluster.name=my-play-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1G
    # resources:
    #   limits:
    #     memory: 1G
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      # 9200 for REST
      - 9200:9200
      # 9300 for inter-node communication
      # - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
